version: 2.1
description: |
    This job requires `pytest-cov` and `coverage` to be installed as `pipenv` `devDependences`.
    Configure pytest and coverage via pyproject.toml.
orbs:
    utils: arrai/utils@1.16.3
executors:
    python312:
        docker:
            - image: cimg/python:3.12
    python311:
        docker:
            - image: cimg/python:3.11
    python310:
        docker:
            - image: cimg/python:3.10
    python39:
        docker:
            - image: cimg/python:3.9
    python38:
        docker:
            - image: cimg/python:3.8
jobs:
    pytest:
        parameters:
            wd:
                description: "Working Directory - where tests should be run in the repo (no trailing slash)."
                type: string
                default: .
            executor:
                type: executor
                default: python39
            resource_class:
                description: "The resource class to use for the job."
                type: enum
                enum: [small, medium, medium+, large, xlarge, 2xlarge, 2xlarge+]
                default: medium
            presetup:
                description: "Any additional pre-setup steps."
                type: steps
                default:
                    - run:
                          name: Install pipenv
                          command: |
                              if ! [ -x "$(command -v pipenv)" ]; then
                                  sudo apt-get install pipenv
                              fi
            setup:
                description: "Any additional setup steps to run (e.g., yum install foo-bar-baz). It occurs before pipenv install. If you passed a wd, you need to cd to it if desired."
                type: steps
                default: []
            config:
                description: "Any additional configuration steps (e.g., cp .env.circleci .env.local). It occurs after pipenv install. If you passed a wd, you need to cd to it if desired."
                type: steps
                default: []
            pytest_args:
                description: "Any additional arguments to pass to pytest."
                type: string
                default: "--cov"
            pipenv_cache_key_version:
                description: "a string that can be changed to bust the pipenv cache."
                type: string
                default: "1"
        executor: <<parameters.executor>>
        resource_class: <<parameters.resource_class>>
        circleci_ip_ranges: true
        environment:
            PIPENV_DONT_LOAD_ENV: 1
        steps:
            - checkout
            - utils/add_ssh_config
            - steps: <<parameters.presetup>>
            - steps: <<parameters.setup>>
            - utils/make_status_shield:
                  status: running
                  color: lightblue
            - utils/rsync_file:
                  file: ~/status.svg
                  remote_file: ${CIRCLE_BRANCH}/${CIRCLE_JOB}.svg
                  host: docs
            - run:
                  name: Keep track of the python version.
                  command: |
                      python --version > /tmp/python.version
            - restore_cache: # ensure this step occurs *before* installing dependencies
                  keys:
                      - pipenv-{{ checksum "/etc/os-release" }}-{{ checksum "/tmp/python.version" }}-<<parameters.pipenv_cache_key_version>>-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
                      - pipenv-{{ checksum "/etc/os-release" }}-{{ checksum "/tmp/python.version" }}-<<parameters.pipenv_cache_key_version>>-{{ .Branch }}
                      - pipenv-{{ checksum "/etc/os-release" }}-{{ checksum "/tmp/python.version" }}-<<parameters.pipenv_cache_key_version>>-main
            - run:
                  name: Setup pipenv environment.
                  command: |
                      cd <<parameters.wd>>
                      pipenv clean
                      pipenv sync --dev | cat; test ${PIPESTATUS[0]} -eq 0
                      echo "import coverage; coverage.process_startup()" > `pipenv run python -c "import sys; print([x for x in sys.path if x.find('.local/share/virtualenvs') != -1 and x.find('site-packages') != -1][0] + '/coverage-all-the-things.pth')"`
            - save_cache:
                  paths:
                      - ~/.local/share/virtualenvs/
                  key: pipenv-{{ checksum "/etc/os-release" }}-{{ checksum "/tmp/python.version" }}-<<parameters.pipenv_cache_key_version>>-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - steps: <<parameters.config>>
            - run:
                  name: Run tests
                  command: |
                      cd <<parameters.wd>>
                      pipenv run pytest <<parameters.pytest_args>>
            - run:
                  name: Build coverage reports
                  command: |
                      cd <<parameters.wd>>
                      pipenv run coverage combine && exit 0
                      pipenv run coverage html
                      pipenv run coverage report | grep -oP '^TOTAL.*\d' | awk '{print $NF}' >> /tmp/.coveragep
                  when: always
            - utils/rsync_folder:
                  when: always
                  folder: htmlcov/
                  remote_folder: ${CIRCLE_BRANCH}/htmlcov_${CIRCLE_JOB}
                  host: docs
            - utils/make_coverage_shield:
                  when: always
                  link: https://${DOCS_HOST}/${CIRCLE_PROJECT_REPONAME}/artifacts/${CIRCLE_BRANCH}/htmlcov_${CIRCLE_JOB}/
            - utils/rsync_file:
                  when: always
                  file: /tmp/coverage.svg
                  remote_file: ${CIRCLE_BRANCH}/${CIRCLE_JOB}.coverage.svg
                  host: docs
            - utils/make_status_shield:
                  when: on_success
                  status: passed
                  color: brightgreen
                  file: ~/status.svg
            - utils/make_status_shield:
                  when: on_fail
                  status: failed
                  color: red
                  file: ~/status.svg
            - utils/rsync_file:
                  when: always
                  file: ~/status.svg
                  remote_file: ${CIRCLE_BRANCH}/${CIRCLE_JOB}.svg
                  host: docs
