version: 2.1
orbs:
    utils: arrai/utils@1.5.0
jobs:
    eslint:
        parameters:
            wd:
                type: string
                default: ~/project
            files:
                type: string
                default: lib/**
            executor:
                type: executor
                default: v12
            config:
                description: "Any additional configuration steps."
                type: steps
                default: []
        executor: <<parameters.executor>>
        resource_class: small
        steps:
            - checkout
            - utils/add_ssh_config
            - run:
                  name: Install additional OS packages
                  command: sudo apt-get install rsync
            - run:
                  name: Install the latest eslint
                  command: sudo npm install -g eslint
            - steps: <<parameters.config>>
            - run:
                  name: Run eslint
                  command: |
                      cd <<parameters.wd>>
                      eslint --color <<parameters.files>> | tee ~/lint
            - utils/make_status_shield:
                  when: on_fail
                  status: errors
                  color: red
                  logo: eslint
            - run:
                  name: Check if we had any warnings
                  when: always
                  command: test ! -s ~/lint
            - utils/make_status_shield:
                  when: always
                  status: warnings
                  color: orange
                  logo: eslint
                  preserve: true
            - utils/make_status_shield:
                  when: on_success
                  status: passed
                  color: brightgreen
                  logo: eslint
            - utils/rsync_file:
                  when: always
                  file: ~/status.svg
                  remote_file: $CIRCLE_BRANCH.$CIRCLE_JOB.svg
                  host: docs
executors:
    v10:
        environment:
            LANG: en_US.UTF-8
        docker:
            - image: circleci/node:10-buster
    v12:
        environment:
            LANG: en_US.UTF-8
        docker:
            - image: circleci/node:12-buster
    v14:
        environment:
            LANG: en_US.UTF-8
        docker:
            - image: circleci/node:14-buster
