version: 2.1
orbs:
    utils: arrai/utils@1.8.0
executors:
    python310:
        environment:
            LANG: C.UTF-8
        docker:
            - image: cimg/python:3.10
    python39:
        environment:
            LANG: C.UTF-8
        docker:
            - image: cimg/python:3.9
    python38:
        environment:
            LANG: C.UTF-8
        docker:
            - image: cimg/python:3.8
    python37:
        environment:
            LANG: C.UTF-8
        docker:
            - image: cimg/python:3.7
    python36:
        environment:
            LANG: C.UTF-8
        docker:
            - image: cimg/python:3.6
    python35:
        environment:
            LANG: C.UTF-8
        docker:
            - image: cimg/python:3.5
jobs:
    flake8:
        parameters:
            flake8_cmd:
                type: string
                default: "flake8"
            wd:
                type: string
                default: ./${CIRCLE_PROJECT_REPONAME}
            executor:
                type: executor
                default: python36
            resource_class:
                type: string
                default: small
            setup:
                description: "Any additional setup steps."
                type: steps
                default:
                    - run:
                          name: Install additional OS packages
                          command: |
                              sudo apt-get update
                              sudo apt-get install rsync
            additional_packages:
                description: "Allows installing additional packages or requirements.txt files."
                type: string
                default: ""
        executor: <<parameters.executor>>
        resource_class: <<parameters.resource_class>>
        steps:
            - checkout
            - utils/add_ssh_config
            - steps: <<parameters.setup>>
            - setup_flake8:
                  wd: <<parameters.wd>>
                  additional_packages: <<parameters.additional_packages>>
            - flake8_errors:
                  flake8_cmd: <<parameters.flake8_cmd>>
                  wd: <<parameters.wd>>
            - utils/make_status_shield:
                  when: on_fail
                  status: errors
                  color: red
                  logo: python
            - utils/make_status_shield:
                  when: on_success
                  status: passed
                  color: brightgreen
                  logo: python
            - utils/rsync_file:
                  when: always
                  file: ~/status.svg
                  remote_file: $CIRCLE_BRANCH/$CIRCLE_JOB.svg
                  host: docs
    flake8_pipenv:
        parameters:
            flake8_cmd:
                type: string
                default: "flake8"
            wd:
                type: string
                default: .
            executor:
                type: executor
                default: python38
            resource_class:
                type: string
                default: small
            setup:
                description: "Any additional setup steps."
                type: steps
                default:
                    - run:
                          name: Install additional OS packages
                          command: sudo apt-get install rsync pipenv
        executor: <<parameters.executor>>
        resource_class: <<parameters.resource_class>>
        steps:
            - checkout
            - utils/add_ssh_config
            - steps: <<parameters.setup>>
            - setup_flake8_pipenv:
                  wd: <<parameters.wd>>
            - flake8_errors_pipenv:
                  flake8_cmd: <<parameters.flake8_cmd>>
                  wd: <<parameters.wd>>
            - utils/make_status_shield:
                  when: on_fail
                  status: errors
                  color: red
                  logo: python
            - utils/make_status_shield:
                  when: on_success
                  status: passed
                  color: brightgreen
                  logo: python
            - utils/rsync_file:
                  when: always
                  file: ~/status.svg
                  remote_file: $CIRCLE_BRANCH/$CIRCLE_JOB.svg
                  host: docs
commands:
    setup_flake8:
        description: "Set up a python virtual environment to run flake8"
        parameters:
            wd:
                type: string
            additional_packages:
                type: string
        steps:
            - run:
                  name: "Set up python virtual environment."
                  command: |
                      cd <<parameters.wd>>
                      python3 -m venv ${HOME}/.venv/
                      . ~/.venv/bin/activate
                      echo "source ${HOME}/.venv/bin/activate" >> $BASH_ENV
                      if [ -f flake8_requirements.txt ]; then
                          pip install -r flake8_requirements.txt <<parameters.additional_packages>> | cat; test ${PIPESTATUS[0]} -eq 0
                      else
                          pip install flake8 <<parameters.additional_packages>> | cat; test ${PIPESTATUS[0]} -eq 0
                      fi
    flake8_errors:
        description: "Run flake8, checking for errors only."
        parameters:
            flake8_cmd:
                type: string
                default: "flake8"
            wd:
                type: string
        steps:
            - run:
                  name: "Check for errors."
                  command: |
                      cd <<parameters.wd>>
                      <<parameters.flake8_cmd>>
    setup_flake8_pipenv:
        description: "Set up a python virtual environment to run flake8"
        parameters:
            wd:
                type: string
        steps:
            - restore_cache: # ensure this step occurs *before* installing dependencies
                  keys:
                      - pipenv-{{ arch }}-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
                      - pipenv-{{ arch }}-{{ .Branch }}-
                      - pipenv-{{ arch }}-
            - run:
                  name: "Set up python virtual environment."
                  command: |
                      cd <<parameters.wd>>
                      pipenv install --dev | cat; test ${PIPESTATUS[0]} -eq 0
            - save_cache:
                  paths:
                      - ~/.local/share/virtualenvs/
                  key: pipenv-{{ arch }}-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
    flake8_errors_pipenv:
        description: "Run flake8, checking for errors only."
        parameters:
            flake8_cmd:
                type: string
                default: "flake8"
            wd:
                type: string
        steps:
            - run:
                  name: "Check for errors."
                  command: |
                      cd <<parameters.wd>>
                      pipenv run <<parameters.flake8_cmd>>
