version: 2.1
orbs:
    utils: arrai/utils@1.8.0
executors:
    lts:
        environment:
            LANG: en_US.UTF-8
        docker:
            - image: cimg/node:lts
    current:
        environment:
            LANG: en_US.UTF-8
        docker:
            - image: cimg/node:current
    v12:
        environment:
            LANG: en_US.UTF-8
        docker:
            - image: cimg/node:12.22
    v14:
        environment:
            LANG: en_US.UTF-8
        docker:
            - image: cimg/node:14.18
    v16:
        environment:
            LANG: en_US.UTF-8
        docker:
            - image: cimg/node:16.13
    v17:
        environment:
            LANG: en_US.UTF-8
        docker:
            - image: cimg/node:17.1
jobs:
    audit:
        parameters:
            wd:
                type: string
                default: ~/project
            executor:
                type: executor
                default: lts
            resource_class:
                description: "The resource class to use for the job."
                type: enum
                enum: [small, medium, medium+, large, xlarge, 2xlarge, 2xlarge+]
                default: small
            setup:
                description: "Any additional setup steps."
                type: steps
                default:
                    - run:
                          name: Install additional OS packages
                          command: |
                              sudo apt-get update
                              sudo apt-get install rsync colorized-logs jq
            report_to:
                description: "E-mail address to send npm audit failure report to."
                type: string
            skip_dev:
                description: "Don't check development dependencies."
                type: boolean
                default: true
        executor: <<parameters.executor>>
        resource_class: <<parameters.resource_class>>
        steps:
            - checkout
            - utils/add_ssh_config
            - steps: <<parameters.setup>>
            - run:
                  name: Install the latest npm
                  command: sudo npm install -g --upgrade npm
            - run:
                  name: Run npm audit
                  command: |
                      cd <<parameters.wd>>
                      npx -y better-npm-audit audit <<# parameters.skip_dev >> -p <</ parameters.skip_dev >> |& tee ~/audit.log
            - run:
                  name: Generate HTML audit report
                  when: on_fail
                  command: cat ${HOME}/audit.log | ansi2html > ${HOME}/audit.html
            - run:
                  name: Count vulnerabilities
                  when: on_fail
                  command: |
                      cd <<parameters.wd>>
                      echo "export TOTAL_VULNERABILITIES=`tail -1 audit.log | grep -Po '^(\d+)' --color=never`" >> $BASH_ENV
            - utils/send_email:
                  when: on_fail
                  to: <<parameters.report_to>>
                  subject: "npm audit report for ${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}"
                  html: "<${HOME}/audit.html"
            - utils/make_status_shield:
                  when: on_fail
                  status: "${TOTAL_VULNERABILITIES}"
                  label: vulnerabilities
                  color: red
                  logo: npm
            - utils/make_status_shield:
                  when: on_success
                  status: "0"
                  label: vulnerabilities
                  color: brightgreen
                  logo: eslint
            - utils/rsync_file:
                  when: always
                  file: ~/status.svg
                  remote_file: $CIRCLE_BRANCH/npm-audit.svg
                  host: docs
