version: 2.1
orbs:
    utils: arrai/utils@1.9.0
executors:
    node14:
        environment:
            LANG: C.UTF-8
        docker:
            - image: cimg/node:14.19-browsers
jobs:
    code_style:
        parameters:
            wd:
                description: "The working directory for the job."
                type: string
                default: ~/project
            executor:
                description: "The executor to use for the job."
                type: executor
                default: node14
            resource_class:
                description: "The resource class to use for the job."
                type: enum
                enum: [small, medium, medium+, large, xlarge, 2xlarge, 2xlarge+]
                default: small
            version:
                description: "The version of prettier to use."
                type: string
                default: ""
            setup:
                description: "Any additional setup steps."
                type: steps
                default: []
            create_badges:
                description: "Generate badges."
                type: boolean
                default: true
        executor: <<parameters.executor>>
        resource_class: <<parameters.resource_class>>
        steps:
            - checkout
            - steps: <<parameters.setup>>
            - run:
                  name: Install the latest npm
                  command: |
                      if [ "$(which npm)" = "/usr/local/bin/npm" ]; then
                          sudo npm install -g --upgrade npm
                      else
                          npm install -g --upgrade npm
                      fi
            - run:
                  name: Install prettier
                  command: |
                      if [ "$(which npm)" = "/usr/local/bin/npm" ]; then
                          sudo npm install -g "prettier$([ ! -z <<parameters.version>> ] && echo "@<<parameters.version>>")"
                      else
                          npm install -g "prettier$([ ! -z <<parameters.version>> ] && echo "@<<parameters.version>>")"
                      fi
            - run:
                  name: Check prettier
                  command: |
                      cd <<parameters.wd>>
                      npx prettier -c .
            - when:
                  condition: <<parameters.create_badges>>
                  steps:
                      - utils/add_ssh_config
                      - run:
                            name: Install additional OS packages
                            command: |
                                sudo apt update
                                sudo apt install rsync
                      - utils/make_status_shield:
                            when: on_fail
                            status: not_quite_prettier
                            color: red
                            logo: prettier
                      - utils/make_status_shield:
                            when: on_success
                            status: prettier
                            color: ff69b4
                            logo: prettier
                      - utils/rsync_file:
                            when: always
                            file: ~/status.svg
                            remote_file: $CIRCLE_BRANCH/$CIRCLE_JOB.svg
                            host: docs
