version: 2.1
orbs:
    utils: arrai/utils@1.5.0
executors:
    node14:
        environment:
            LANG: C.UTF-8
        docker:
            - image: cimg/node:14.18-browsers
        resource_class: small
jobs:
    code_style:
        parameters:
            wd:
                type: string
                default: ~/project
            executor:
                description: "Execution environment for the test job."
                type: executor
                default: node14
            resource_class:
                type: string
                default: medium
            version:
                type: string
                default: ""
            setup:
                description: "Any additional setup steps."
                type: steps
                default:
                    - run:
                          name: Install additional OS packages
                          command: |
                              sudo apt-get update
                              sudo apt-get install rsync
        executor: <<parameters.executor>>
        resource_class: small
        steps:
            - checkout
            - utils/add_ssh_config
            - steps: <<parameters.setup>>
            - run:
                  name: Install prettier
                  command: |
                      sudo npm install -g "prettier$([ ! -z <<parameters.version>> ] && echo "@<<parameters.version>>")"
            - run:
                  name: Check prettier
                  command: |
                      cd <<parameters.wd>>
                      npx prettier -c .
            - utils/make_status_shield:
                  when: on_fail
                  status: not_quite_prettier
                  color: red
                  logo: prettier
            - utils/make_status_shield:
                  when: on_success
                  status: prettier
                  color: ff69b4
                  logo: prettier
            - utils/rsync_file:
                  when: always
                  file: ~/status.svg
                  remote_file: $CIRCLE_BRANCH/$CIRCLE_JOB.svg
                  host: docs
